version: '3'
services:
  web:
    build: .
    command: "scripts/docker-wait-pgsql; python scripts/migrate.py; python manage.py runserver 0.0.0.0:80"
    entrypoint: scripts/docker-run
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/code
    ports:
      - "80:80"
  db:
    build:
      context: docker/database/
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/scripts
      - /var/lib/postgresql/9.6/main
    entrypoint: scripts/docker-run
    expose:
      - 5432
    command: "/usr/lib/postgresql/9.6/bin/postgres -D /var/lib/postgresql/9.6/main -c config_file=/etc/postgresql/9.6/main/postgresql.conf"
    user: postgres